# Generated by Django 5.2.3 on 2025-06-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('skin_tone', models.CharField(max_length=50)),
                ('height', models.PositiveIntegerField()),
                ('body_shape', models.CharField(max_length=50)),
                ('body_size', models.CharField(max_length=50)),
                ('face_shape', models.CharField(max_length=50)),
                ('hair_length', models.CharField(max_length=50)),
                ('hair_texture', models.CharField(max_length=50)),
            ],
        ),
    ]
